name: Build Docker

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: build
      env:
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        REGISTRY_PASSWD: ${{ secrets.REGISTRY_PASSWD }}
      run: |
        cd $GITHUB_WORKSPACE
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --name mybuilder --bootstrap --use
        docker login -u $REGISTRY_USER -p $REGISTRY_PASSWD registry.cn-hangzhou.aliyuncs.com
        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t docker.spjsjg.v6.navy:8082/erpnext:latest --push .
        rm -rf ~/.docker
